version: '3.9'
services:
  sd-material-nbs-v2-app:
    container_name: sd-material-nbs-v2-app
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile
    ports:
      - '8080:3000'
    environment:
      AWS_ACCESS_KEY_ID: xxxxx
      AWS_SECRET_ACCESS_KEY: xxxxx
