on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Standard

jobs:
  ci:
    name: CI - Build and Test
    runs-on: [vs-sap]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm
          registry-url: https://npm.pkg.github.com/
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHA_PACKAGES }}
      - name: Lint App
        run: npm run lint
      - name: Test App
        run: npm run test
      - name: Build App
        run: npm run build
      - name: Sonar Analysis
        uses: grupoboticario/actions-ci-sonarcloud@v1
        if: ${{ vars.SONAR_ENABLED == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_PACKAGES }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
  ci_docker:
    name: CI - Docker
    runs-on: [vs-sap]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Docker Build and Push
        uses: grupoboticario/actions-ci-alquimia@v2
        with:
          build-platform: linux/amd64
          docker-secrets: |
            NODE_AUTH_TOKEN=${{ secrets.GHA_PACKAGES }}
          dockerfile-path: dockerfiles/Dockerfile
  cd_dev:
    name: CD - dev
    if: ${{ success() && github.event_name != 'pull_request' && github.actor != 'dependabot[bot]' }}
    needs: [ci, ci_docker]
    runs-on: [vs-sap]
    environment:
      name: dev
      url: ${{ steps.actions-cd-app.outputs.environment-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Deploy Infra
        uses: grupoboticario/actions-cd-alquimia@v2
        id: actions-cd-infra
        with:
          environment: aws-btp-dev
          type: infra
      - name: Deploy App
        uses: grupoboticario/actions-cd-alquimia@v2
        id: actions-cd-app
        with:
          environment: aws-btp-dev
          type: app
  cd_prd:
    name: CD - prd
    if: ${{ success() && github.ref == 'refs/heads/main' }}
    needs: [cd_dev]
    runs-on: [vs-sap]
    environment:
      name: prd
      url: ${{ steps.actions-cd-app.outputs.environment-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Deploy Infra
        uses: grupoboticario/actions-cd-alquimia@v2
        id: actions-cd-infra
        with:
          environment: aws-btp-prd
          type: infra
      - name: Deploy App
        uses: grupoboticario/actions-cd-alquimia@v2
        id: actions-cd-app
        with:
          environment: aws-btp-prd
          type: app
