on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '.scafflater/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.scafflater/**'
  workflow_dispatch:

name: Standard

permissions: write-all

env:
  namespace: s4hana-fiori

  #Config Deploy Fiori
  app_name: sd-material-nbs-v2-app
  app_name_back:
  app_cloud_service: materialnbsv2_service

  # Config Deploy Pipeline
  aws_region: us-east-1
  aws_role: arn:aws:iam::837663801964:role/github_actions-ecr_access
  sm_aws_role: arn:aws:iam::837663801964:role/github_actions-secrets_access

jobs:
  ci:
    name: CI
    runs-on: [self-hosted, vs-demanda-abastecimento]
    environment: ci
    steps:
      - uses: actions/checkout@v6
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/checkout@v6
        if: ${{ github.event_name != 'pull_request_target' }}

      - name: Add npm bin to PATH
        run: |
          echo "${{ github.workspace }}/node_modules/.bin" >> $GITHUB_PATH

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64

      - name: Configure AWS Credentials
        if: github.event_name != 'pull_request_target'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.aws_role }}
          aws-region: us-east-1

      - name: Create ECR repository
        if: github.event_name != 'pull_request_target'
        continue-on-error: true
        run: >
          aws ecr create-repository --repository-name ${{ env.app_name }} 
          --image-scanning-configuration scanOnPush=true || 
          echo 'ECR repository already exists'

      - name: Set ECR policy
        if: github.event_name != 'pull_request_target'
        continue-on-error: true
        run: >
          aws ecr set-repository-policy --repository-name ${{ env.app_name }}  
          --policy-text $(cat policy.txt) 
          || echo 'Policy already set'

      - name: Login to Amazon ECR
        if: github.event_name != 'pull_request_target'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: name/app:latest

      - name: Build and push
        if: github.event_name != 'pull_request_target'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.app_name }}:ci-v${{ github.run_number }}

  cd_dev:
    name: CD - DEV - KYMA
    if: ${{ success() && github.event_name != 'pull_request_target' }}
    needs: ci
    runs-on: [self-hosted, vs-demanda-abastecimento]
    environment: dev
    steps:
      - uses: actions/checkout@v6
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/checkout@v6
        if: ${{ github.event_name != 'pull_request_target' }}

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v2.1
        with:
          version: 'v1.21.0'

      - uses: azure/setup-helm@v2.1
        if: hashFiles('helm/values.yaml') != ''
        with:
          version: 'v3.8.2'

      - name: Configure AWS Credentials
        if: github.event_name != 'pull_request_target'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.sm_aws_role }}
          aws-region: us-east-1

      - name: Read secrets from AWS Secrets Manager into environment variables
        uses: bitovi/github-actions-aws-secrets-manager@v2.0.0
        with:
          secrets: |
            KUBECONFIG_DEV
          parse-json: false

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ env.KUBECONFIG_DEV }}

      - name: Remove K8SCONFIG
        run: |
          kubectl cluster-info
          echo 'K8SCONFIG=' >> $GITHUB_ENV

      # Prepare deployments
      - name: Render Auth YAML
        uses: nowactions/envsubst@v1
        with:
          input: ./deployment/serviceInstances/authentication.yaml.tpl
          output: ./deployment/authentication.yaml
        env:
          NAME_APP: ${{ env.app_name }}
          NAMESPACE: ${{ env.namespace }}

      - name: Render Deployment YAML
        uses: nowactions/envsubst@v1
        with:
          input: ./deployment/deployment.yaml.tpl
          output: ./deployment/deployment.yaml
        env:
          NAME_APP: ${{ env.app_name }}
          NAME_CLOUD_SERVICE: ${{ env.app_cloud_service }}

      - name: Render App Repo Host YAML
        uses: nowactions/envsubst@v1
        with:
          input: ./deployment/serviceInstances/html5AppsRepoHost.yaml.tpl
          output: ./deployment/html5AppsRepoHost.yaml
        env:
          NAME_APP: ${{ env.app_name }}

      # If is need destination.
      - name: Render Destination YAML
        uses: nowactions/envsubst@v1
        with:
          input: ./deployment/serviceInstances/destination.yaml.tpl
          output: ./deployment/destination.yaml
        env:
          NAME_APP: ${{ env.app_name }}

      # Deploy destination if this required.
      - name: Deploy Destination
        uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          namespace: ${{ env.namespace }}
          manifests: |
            deployment/destination.yaml
          strategy: none

      - uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          namespace: ${{ env.namespace }}
          manifests: |
            deployment/authentication.yaml
            deployment/html5AppsRepoHost.yaml
            deployment/deployment.yaml
          images: |
            837663801964.dkr.ecr.us-east-1.amazonaws.com/${{ env.app_name }}:ci-v${{ github.run_number }}
          imagepullsecrets: |
            aws-ecr-auth
          strategy: none

      - name: App install
        if: hashFiles('helm/values.yaml') != ''
        run: helm upgrade -i ${{ env.app_name }} ${{ github.workspace }}/./helm -n ${{ env.app_name }}

  cd_prd:
    name: CD - PRD - KYMA
    if: ${{ success() && github.ref == 'refs/heads/main' }}
    needs: cd_dev
    runs-on: [self-hosted, vs-demanda-abastecimento]
    environment: prd
    steps:
      - uses: actions/checkout@v6
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/checkout@v6
        if: ${{ github.event_name != 'pull_request_target' }}

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v2.1
        with:
          version: 'v1.21.0'

      - uses: azure/setup-helm@v2.1
        if: hashFiles('helm/values.yaml') != ''
        with:
          version: 'v3.8.2'

      - name: Configure AWS Credentials
        if: github.event_name != 'pull_request_target'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.sm_aws_role }}
          aws-region: us-east-1

      - name: Read secrets from AWS Secrets Manager into environment variables
        uses: bitovi/github-actions-aws-secrets-manager@v2.0.0
        with:
          secrets: |
            KUBECONFIG_PRD
          parse-json: false

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ env.KUBECONFIG_PRD }}

      - name: Remove K8SCONFIG
        run: |
          kubectl cluster-info
          echo 'K8SCONFIG=' >> $GITHUB_ENV

      # Prepare deployments
      - name: Render Auth YAML
        uses: nowactions/envsubst@v1
        with:
          input: ./deployment/serviceInstances/authentication.yaml.tpl
          output: ./deployment/authentication.yaml
        env:
          NAME_APP: ${{ env.app_name }}
          NAMESPACE: ${{ env.namespace }}

      - name: Render Deployment YAML
        uses: nowactions/envsubst@v1
        with:
          input: ./deployment/deployment.yaml.tpl
          output: ./deployment/deployment.yaml
        env:
          NAME_APP: ${{ env.app_name }}
          NAME_CLOUD_SERVICE: ${{ env.app_cloud_service }}

      - name: Render App Repo Host YAML
        uses: nowactions/envsubst@v1
        with:
          input: ./deployment/serviceInstances/html5AppsRepoHost.yaml.tpl
          output: ./deployment/html5AppsRepoHost.yaml
        env:
          NAME_APP: ${{ env.app_name }}

      # If is need destination.
      - name: Render Destination YAML
        uses: nowactions/envsubst@v1
        with:
          input: ./deployment/serviceInstances/destination.yaml.tpl
          output: ./deployment/destination.yaml
        env:
          NAME_APP: ${{ env.app_name }}
          NAMESPACE: ${{ env.namespace }}

      # Deploy destination if this required.
      - name: Deploy Destination
        uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          namespace: ${{ env.namespace }}
          manifests: |
            deployment/destination.yaml
          strategy: none

      - uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          namespace: ${{ env.namespace }}
          manifests: |
            deployment/authentication.yaml
            deployment/html5AppsRepoHost.yaml
            deployment/deployment.yaml
          images: |
            837663801964.dkr.ecr.us-east-1.amazonaws.com/${{ env.app_name }}:ci-v${{ github.run_number }}
          imagepullsecrets: |
            aws-ecr-auth
          strategy: none

      - name: App install
        if: hashFiles('helm/values.yaml') != ''
        run: helm upgrade -i ${{ env.app_name }} ${{ github.workspace }}/./helm -n ${{ env.app_name }}
